import type { Metadata } from "next"
import { Breadcrumbs } from "@/components/breadcrumbs"
import { CookieDeclaration } from "@/components/cookie-declaration"

export const metadata: Metadata = {
  title: "Cookies — Dual Perspective Digital",
  description:
    "Cookie policy and cookie declaration for dualperspective.digital. Manage your consent preferences and review cookies used on this site.",
  alternates: {
    canonical: "/cookies",
    languages: { en: "/cookies", es: "/es/cookies" },
  },
}

export default function CookiesPage() {
  return (
    <main className="min-h-screen px-6 md:px-12 lg:px-20 py-20 md:py-24">
      <div className="max-w-4xl mx-auto">
        <Breadcrumbs 
          items={[{ label: "Cookies" }]} 
          locale="en"
        />
        <h1 className="text-3xl md:text-4xl lg:text-5xl tracking-tight leading-tight mb-6">
          Cookies
        </h1>
        <p className="text-base md:text-lg text-muted-foreground leading-relaxed mb-10">
          We use cookies to operate the site and, with your consent, to understand usage and improve performance. You can
          change your preferences at any time via the banner.
        </p>

        <div className="border-t border-border/60 pt-10">
          <h2 className="text-xl md:text-2xl tracking-tight mb-4">Cookie declaration</h2>
          <p className="text-sm md:text-base text-muted-foreground leading-relaxed mb-6">
            The list below is automatically generated by our consent manager.
          </p>

          <CookieDeclaration locale="en" />
        </div>
      </div>
    </main>
  )
}


